### ISSUE TITLE
With the Airportitlwm.kext on macOS from original configuration Wi-Fi is not working/broken on Windows

### ISSUE THREAD

**Issue by drinvincibilis** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#11]
So, after pretty successful Big Sur 11.1 installation based on the original config.plist having Airportitlwm.kext enabled the Wi-Fi under macOS was running quite fine.
However:

When booting into Windows the Wi-Fi device seems to be completely broken
![image](https://user-images.githubusercontent.com/20166851/104135240-3b954880-538f-11eb-8296-95b6e8e3d502.png)

Nothing helps: driver update, reinstall, disabling/enabling.

This is reported here: https://github.com/OpenIntelWireless/itlwm/issues/329

Any suggestions as always much appreciated.

**Comment by racka98** [comment]
I don't have Windows installed on my laptop so i don't know how to fix this. The post you linked seems to know what's wrong

**Comment by drinvincibilis** [comment]
Indeed it's related to OpenCore boot.
Solution: do not boot Windows from OpenCore. Boot it by selecting Windows Boot Manager from UEFI boot menu. F12 on T450s
