### ISSUE TITLE
Missing Boot Chime

### ISSUE THREAD

**Issue by batman38102** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#12]
I've already managed to solve this by adding the needed files and entries in config.plist but it's missing from the new EFI provided. Not sure if this was done for a reason or a preference for the developer.

**Comment by racka98** [comment]
> I've already managed to solve this by adding the needed files and entries in config.plist but it's missing from the new EFI provided. Not sure if this was done for a reason or a preference for the developer.

I did it on purpose. It was causing sound loss on boot for some people.

**Comment by batman38102** [comment]
Never had that issue myself on T450 but thanks it works fine regardless!
