### ISSUE TITLE
Big Sur 11.2 not showing in software updates

### ISSUE THREAD

**Issue by martin-lx** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#13]
I am using your EFI on an X250 and everything works great except that Big Sur 11.2 is not showing up in software updates.

My config is pretty standard (Core i5 5200U, Intel 7265). OpenCore and Big Sur and installed on an M.2 drive, Windows is on the main SATA drive. iCloud is configured and working without issue. Continuity and HandOff are working. Sleep works. 

The drive seal for the Big Sur volume shows up as broken in diskutil but I read elsewhere that this was not an issue as long as I also had "Snapshot Sealed: Yes".

I am using the latest version of the repo (Opencore 0.6.6). The only things I changed in Config.plist are adding the S/N, disabling verbose boot, hiding the Clear NVRAM / Recovery options (HideAuxiliary), and adding the YogaSMC kext.

Any idea what I can do? 

I also would like to take this opportunity to thank you for your work, this is the most stable and clean Hackintosh laptop I ever had.

**Comment by racka98** [comment]
> I am using your EFI on an X250 and everything works great except that Big Sur 11.2 is not showing up in software updates.
> 
> My config is pretty standard (Core i5 5200U, Intel 7265). OpenCore and Big Sur and installed on an M.2 drive, Windows is on the main SATA drive. iCloud is configured and working without issue. Continuity and HandOff are working. Sleep works. 
> 
> The drive seal for the Big Sur volume shows up as broken in diskutil but I read elsewhere that this was not an issue as long as I also had "Snapshot Sealed: Yes".
> 
> I am using the latest version of the repo (Opencore 0.6.6). The only things I changed in Config.plist are adding the S/N, disabling verbose boot, hiding the Clear NVRAM / Recovery options (HideAuxiliary), and adding the YogaSMC kext.
> 
> Any idea what I can do? 
> 
> I also would like to take this opportunity to thank you for your work, this is the most stable and clean Hackintosh laptop I ever had. 

That's probably a macOS issue. You try installing from Appstore. Download the latest macOS installer and install it that way. Snapshots has introduced a lot of issues with updates

**Comment by martin-lx** [comment]
That worked, thanks.
