### ISSUE TITLE
Stuck at Apple logo past boot sequence but before installer

### ISSUE THREAD

**Issue by Admiral124** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#16]
**Describe the bug**
The system seems to be unable to make it to the installer screen. System locks up at an Apple logo

**To Reproduce**
1. Followed guide through to step 10 (including setting correct bios flags) using a macOS virtual machine to create installation tool
2. The system goes through the boot process and freezes just before the installer

**Screenshots**
[Where the system finally freezes](https://imgur.com/a/vqTpMDu)
[The last section seen before the Apple loading bar](https://imgur.com/y5mDrYH)

**macOS Info:**
 - OS: Big Sur
 - Version 11.2.1 (20D75)
 - Laptop Model: T450s BIOS version JBET72WW (1.36)

**Comment by racka98** [comment]
Wait a minute, does your laptop have the Geforce 940M graphics?

**Comment by Admiral124** [comment]
No, it uses integrated graphics. Here are the complete specs
```
System:    Host: t450s Kernel: 5.10.0-3-amd64 x86_64 bits: 64 Desktop: sway 1.5 Distro: Debian GNU/Linux bullseye/sid 
Machine:   Type: Laptop System: LENOVO product: 20BXCTO1WW v: ThinkPad T450s serial: <superuser required> 
           Mobo: LENOVO model: 20BXCTO1WW v: SDK0E50512 STD serial: <superuser required> UEFI [Legacy]: LENOVO 
           v: JBET72WW (1.36 ) date: 02/23/2019 
Battery:   ID-1: BAT0 charge: 16.4 Wh condition: 17.0/23.2 Wh (73%) 
           ID-2: BAT1 charge: 15.2 Wh condition: 15.8/23.2 Wh (68%) 
CPU:       Info: Dual Core model: Intel Core i5-5200U bits: 64 type: MT MCP L2 cache: 3 MiB 
           Speed: 2037 MHz min/max: 500/2700 MHz Core speeds (MHz): 1: 2037 2: 1948 3: 1980 4: 1988 
Graphics:  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel 
           Device-2: Lite-On Integrated Camera type: USB driver: uvcvideo 
           Display: server: No display server data found. Headless machine? 
           Message: No advanced graphics data found on this system. 
Audio:     Device-1: Intel Broadwell-U Audio driver: snd_hda_intel 
           Device-2: Intel Wildcat Point-LP High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.10.0-3-amd64 
Network:   Device-1: Intel Ethernet I218-V driver: e1000e 
           IF: enp0s25 state: down mac:  
           Device-2: Intel Wireless 7265 driver: iwlwifi 
           IF: wlan0 state: up mac: 
Bluetooth: Device-1: Intel Bluetooth wireless interface type: USB driver: btusb 
           Report: ID: hci0 state: up running bt-v: 2.1 address: 
Drives:    Local Storage: total: 119.24 GiB used: 2.53 GiB (2.1%) 
           ID-1: /dev/sda vendor: Toshiba model: THNSNJ128GCSU size: 119.24 GiB 
Partition: ID-1: / size: 115.93 GiB used: 2.53 GiB (2.2%) fs: ext4 dev: /dev/sda1 
Swap:      ID-1: swap-1 type: partition size: 976 MiB used: 0 KiB (0.0%) dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 36.0 C mobo: 0.0 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 125 Uptime: 2m Memory: 11.41 GiB used: 484.2 MiB (4.1%) Shell: Zsh inxi: 3.3.01 
```

**Comment by racka98** [comment]
There's probably a setting in your BIOS causing it to fail. Normally when it fails at the 2nd boot screen it's because of unsupported GPU or a setting in the BIOS. Since it gets past the 1st verbose screen it mean the EFI is fine.

Can first reset bios settings to default and save. Reboot back into BIOS and set it up like in the readme of this repo

**Comment by Admiral124** [comment]
Reset the bios to default, saved and rebooted, then set it up according to the readme. Still the exact same result. 
As an aside, I am not going to try remaking the install USB with a different flash drive just to rule out that as a possibility.

**Comment by racka98** [comment]
> Reset the bios to default, saved and rebooted, then set it up according to the readme. Still the exact same result. 
> As an aside, I am going to try remaking the install USB with a different flash drive just to rule out that as a possibility.

You also try setting your usb port to 2.0 mode

**Comment by Admiral124** [comment]
So using a new drive didn't help and neither did changing the system to USB 2.0 only. Overnight I decided to try downloading Catalina and writing it to another drive. It was able to get a little further - the loading bar progresses to roughly 20% - then it flashes "Failed to send exception EXC_CORPSE_NOTIFY. error code: -308" for three process ids and proceeds to shut the system down.

**Comment by racka98** [comment]
> So using a new drive didn't help and neither did changing the system to USB 2.0 only. Overnight I decided to try downloading Catalina and writing it to another drive. It was able to get a little further - the loading bar progresses to roughly 20% - then it flashes "Failed to send exception EXC_CORPSE_NOTIFY. error code: -308" for three process ids and proceeds to shut the system down.

Are you on latest BIOS? Is secure boot turned off and BIOS set UEFI Only mode with CSM Support On?

Can you mention the exact model number of your T450

**Comment by Admiral124** [comment]
Yes, all of the bios settings are set as per what is in the readme. It was on bios 1.36(JBET72WW) but I updated it to 1.37(JBET73WW) (current release) and it didn't change anything.
It is a T450s with the model number 20BXCTO1WW

**Comment by racka98** [comment]
> > > So using a new drive didn't help and neither did changing the system to USB 2.0 only. Overnight I decided to try downloading Catalina and writing it to another drive. It was able to get a little further - the loading bar progresses to roughly 20% - then it flashes "Failed to send exception EXC_CORPSE_NOTIFY. error code: -308" for three process ids and proceeds to shut the system down.
> > 
> > Are you on latest BIOS? Is secure boot turned off and BIOS set UEFI Only mode with CSM Support On?
> > 
> > Can you mention the exact model number of your T450
> 
> Yes, all of the bios settings are set as per what is in the readme. It was on bios 1.36(JBET72WW) but I updated it to 1.37(JBET73WW) (current release) and it didn't change anything.
> It is a T450s with the model number 20BXCTO1WW

Can you try connecting an external display and see if it will work

**Comment by Admiral124** [comment]
> > > > So using a new drive didn't help and neither did changing the system to USB 2.0 only. Overnight I decided to try downloading Catalina and writing it to another drive. It was able to get a little further - the loading bar progresses to roughly 20% - then it flashes "Failed to send exception EXC_CORPSE_NOTIFY. error code: -308" for three process ids and proceeds to shut the system down.
> > > 
> > > 
> > > Are you on latest BIOS? Is secure boot turned off and BIOS set UEFI Only mode with CSM Support On?
> > > Can you mention the exact model number of your T450
> > 
> > 
> > Yes, all of the bios settings are set as per what is in the readme. It was on bios 1.36(JBET72WW) but I updated it to 1.37(JBET73WW) (current release) and it didn't change anything.
> > It is a T450s with the model number 20BXCTO1WW
> 
> Can you try connecting an external display and see if it will work

That's a good idea but unfortunately it didn't really help. The notebook still stops at the Apple loading bar and the external display is just a black screen. Honestly, I'm kind of stumped. I'm not sure what exactly is preventing this particular machine from reaching the installer.

**Comment by cchyswy** [comment]
My model is also 20BXCTO1WW BIOS1.37 and I can install Mojave Catalina

**Comment by patsore** [comment]
Hello!  I have the same issue, though are models differ - mine is 20BX001PUS. A point that we have in common is that we made the usb with virtual machines, so that might be the issue?

**Comment by racka98** [comment]
> Hello!  I have the same issue, though are models differ - mine is 20BX001PUS. A point that we have in common is that we made the usb with virtual machines, so that might be the issue?

Might be. How did you pass-through your USB drive to the VM?

**Comment by patsore** [comment]
A prompt came up and I just routed the USB to the vm. (I used VmWare Workstation instead of VirtualBox)

**Comment by racka98** [comment]
Might be something wonky with USB pass-through. I always use VirtualBox and the USB Extension Pack and it has always worked for me with enabling USB 3.0 pass-through

**Comment by patsore** [comment]
I'm gonna try making a vm on virtualbox, and report back.

**Comment by patsore** [comment]
Okay I found a tool called TINU. (https://github.com/ITzTravelInTime/TINU/releases/tag/2.1_PUBLIC_60). And it shows the big sur installer as damaged, so if OP has the same thing, we might have found the problem.

**Comment by patsore** [comment]
Okay I looked around, turns out the reason it said installer was damaged was because that version of the tool didn't have support for big sur.

**Comment by patsore** [comment]
I also noticed that when I executed the "sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume" the "copying files" was stuck at 0%. Or I might've just not waited long enough, so I'll try that.

**Comment by patsore** [comment]
Seems it didn't make a difference - still stuck.

**Comment by patsore** [comment]
![folders](https://user-images.githubusercontent.com/80210497/110305244-378b4d00-8005-11eb-93cc-ff57601debff.png)
Maybe there's a problem with the files?

**Comment by racka98** [comment]
I don't think so. The files are fine. I've tested them on my machine and everything works. Have you tried an older build like 0.6.3 v1 in the releases page? If that also doesn't work then there's probably a setting your are missing.

Try using efi files from that release and see if it makes a difference

**Comment by patsore** [comment]
My settings were reset to default and copied from yours, so, I doubt any problems would come from them. With older EFI versions still stuck.

**Comment by patsore** [comment]
Okay, so I used the mojave os. Then I managed to boot into installer. So the problem was most likely the OS.

**Comment by racka98** [comment]
You could have use Catalina then update to Big Sur

**Comment by patsore** [comment]
Okay, so I managed to install mojave, then, using the mojave hackintosh I made a bootable usb with the not-latest big sur, and then everything was smooth sailing.

**Comment by racka98** [comment]
I guess the latest Big Sur installer has some issues. Glad it was all sorted out
