### ISSUE TITLE
T450s Static noise when connected to audio jack

### ISSUE THREAD

**Issue by ZackVas** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#18]
Hello!
I have a problem where I cannot seem to fix the static audio noises in my headphones when plugged into the audio jack.
I have tried installing alc_fix_swift from the utilities folder using the instructions from readme 2 times, and yet the static noise is still there. 
I'm new to opencore, so maybe I missed something
Hope you can help me with this!
Thanks!

**Comment by racka98** [comment]
https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/issues/15#issuecomment-788554414

**Comment by ZackVas** [comment]
By first boot, do you mean I will have to reinstall Mac OS and put the computer to sleep, then turn it on and the issue will be gone?

**Comment by racka98** [comment]
> By first boot, do you mean I will have to reinstall Mac OS and put the computer to sleep, then turn it on and the issue will be gone?

No. Whenever you turn on the laptop (first boot) close the laptop lid so it can sleep and then open the lid and the static noise should be gone. If you shutdown your laptop everytime you are done with it this process can be annoying but i personally rarely shutdown the laptop. I just pit it to sleep and I'm done. Sleep/wake is very stable with this EFI and you won't ever get a kernel panic from it

**Comment by ZackVas** [comment]
Okay, I will try it soon and let you know if it worked. Thanks so much for your help!

**Comment by ZackVas** [comment]
I have tried turning on the laptop, closing the lid, wait for a bit so it can sleep and then open it and it wakes up but the static noise is still there. I tried to do it with the cable plugged in and with it unplugged. I also tried to put it to sleep by both closing it and clicking sleep on the lock screen. None of these worked, unfortunately.

**Comment by racka98** [comment]
It worked for me. Although i haven't tested it on the new updates as I don't use headphones on my laptop anymore. Let me find some wired headphones and see what's going on

**Comment by ZackVas** [comment]
Thanks so much! Sorry for the inconvenience.

**Comment by ZackVas** [comment]
So, I was curious and I tried to find a solution myself. Since you said that it is not an issue that occurred in the previous version, I have tried the "Big Sur Opencore v0.6.3 v1" release on a usb, and unexpectedly to me, my issue was gone. The laptop started up, I put it to sleep, then i awake it and plug in my headphones and my audio finally works properly, with no static. So, from this I can gather that this is definitely an issue that happened with an update.

**Comment by macintoshben** [comment]
I just used your guide on my T450s last night, and it has been working quite nicely and is extremely stable. I really appreciate your work! 

I did, however, have this audio glitch. At first, there was simply no audio through the headphones. Then, I restarted, and the static appeared. The static that was coming through the headphone jack was very loud, to the point that I got my cheap headphones to try to resolve the problem. I was eventually able to get the audio back by plugging the headphones in with the lid closed, but I don't really trust it enough to actually use it, due to the loud static. Does anyone know where the static comes from?

**Comment by racka98** [comment]
> I just used your guide on my T450s last night, and it has been working quite nicely and is extremely stable. I really appreciate your work! 
> 
> I did, however, have this audio glitch. At first, there was simply no audio through the headphones. Then, I restarted, and the static appeared. The static that was coming through the headphone jack was very loud, to the point that I got my cheap headphones to try to resolve the problem. I was eventually able to get the audio back by plugging the headphones in with the lid closed, but I don't really trust it enough to actually use it, due to the loud static. Does anyone know where the static comes from?

It a known issue with the codec in this laptop. The current fix is to close the laptop lid and let it go to sleep then wake it up and plug your headphones. This will work until you turn off or reboot the computer. Then you'll have to get it to sleep again to fix the issue. There has multiple attempts to fix but no luck

**Comment by peace-division** [comment]
For me the sound doesn't work at all, i managed to install Monterey but sound doesn't work. Everything else works fine !

**Comment by tbilic14** [comment]
Didn't work for me either on Monterey. I switched to Big Sur and it just worked.

**Comment by racka98** [comment]
Solution in here: https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/issues/37
