### ISSUE TITLE
Black screen after picking OpenCore

### ISSUE THREAD

**Issue by eqlion** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#2]
**Describe the bug**
After creating the boot thumbdrive with OpenCore.

**To Reproduce**
I created the bootdrive using Ubuntu and followed the [first method](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#method-1). Afterwards, I copied the `BaseSystem.dmg` and the `BaseSystem.chunklist` (which I got via macrecovery.py for Big Sur; tried Catalina too, same result) to the `com.apple.recovery.boot` folder at the root of the drive. After that I downloaded the EFI folder from this repo and placed it along the `com.apple.recovery.boot` folder at the root. 

Then I restarted the laptop, went into BIOS and changed all the options from the README.

When choosing the thumbdrive as a startup device, I was greeted with OpenCore screen with icons, where I clicked the first one. Then the screen went black (but lit up). Sometimes it stays this way for more than 20 minutes until I manually turn off the laptop, other times it just reboots randomly. I tried using DEBUG version of OpenCore in hopes of getting the logs and finding the problem but to no avail (I replaced the files from the EFI folder from this repo to the files from the DEBUG release, as stated [here](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps): everything stays the same, even if I delete `OpenCanopy.efi` and remove the lines for it from config.plist.

**Expected behavior**
The installation starts.

**Hardware:**
ThinkPad T450, i5-5300U, HD Graphics 5500, 8 GB, Intel 7265

**Additional context**
I've noticed that the `config.plist` in the repo is capitalized, however it is not in the guides. Nonetheless, changing it (nor not changing it) doesn't help to solve the issue.

[The content of my drive (roor)](https://i.imgur.com/xJTNzH6.png)

[The content of my drive (EFI/OC folder)](https://i.imgur.com/a9PUodo.png)

I'd be happy to provide any additional info that might be required and if I install the MacOS successfully, I'd love to contribute to writing a detailed guide, if you want any help! Thanks in advance!

**Comment by cchyswy** [comment]
I feel that there is a problem with your installation program. You can use gibMacOS to download the image and make a boot disk.
https://github.com/corpnewt/gibMacOS

**Comment by racka98** [comment]
With Big Sur you can't use windows or linux to make the usb. You need macos. 
If you don't have a real mac you can use a pre-made Virtual Machine iso of Catalina. See this guide: https://www.wikigain.com/install-macos-catalina-on-virtualbox-on-windows/

After that use gibMacOS to download Big Sur (with this you won't need to sign in your Apple ID on the virtual machine and it's more reliable in downloading).

1. Download gibMacOS: https://github.com/corpnewt/gibMacOS
2. Right click then choose open on gibMacOS.command (it will launch in terminal)
3. Choose a number from the list provided (Big Sur will probably be number 1 in the list as 11.0.1 Public release)
4. It will download Big Sur (12.19 GB) and it will place the contents in gibMacOS folder under macOS Downloads/publicrelease/11.0.1 macOS Big Sur.
5. Open the InstallAssistant.pkg that will extract the installer to your Applications folder
6. Format your usb drive to Mac OS Extentended (Journaled) with GUID partition scheme
7. Now run: sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume
MyVolume will be replaced by the name you gave to your usb when formatting it. Or you could name the usb as MyVolume when you were formatting.
This will create the bootable usb that works on a real mac.
8. Now you can proceed with "Setting up OpenCore's EFI environment" from [here](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer).
9. Copy the OC and BOOT files from my EFI and fireup the installer.
10. Select Install macOS Big Sur from the boot menu and not the recovery partition.

I should probably add this info in the readme. As a lot of people have had this issue.

**Comment by eqlion** [comment]
@racka98 Thank you, this worked wonders!

**Comment by robjvan** [comment]
Didn't work for me.  Getting "EXITBS:START" error on a t450s using Big Sur 11.2.1 created on a BS VM

**Comment by racka98** [comment]
> Didn't work for me.  Getting "EXITBS:START" error on a t450s using Big Sur 11.2.1 created on a BS VM

Some people have reported having issues with launching Big Sur 11.2.1 installer. Try with 11.0 (first public release) or Catalina installer then you can update to the latest

**Comment by robjvan** [comment]
Tried again with an 11.0.1 ISO.  Wiped the drive and did the createinstallmedia command again.  Then copied your custom EFI folder over to the EFI partition.  It boots, but still gets stuck at EXITBS:START shortly after some gibberish about OS.dmg.root_hash

**Comment by robjvan** [comment]
If I have CSM Support on it BIOS, the laptop will reboot automatically after hitting the error.  If I have CSM support = No, it stays locked at the EXITBS error.  This is getting frustrating - I've followed your guide again and again, and it just doesn't work for me.

I'm using Arch, and have Big Sur working in VMWare so I'm comfortable with semi-complicated installs but I just can't get this to cooperate.  Am I being too impatient and need to leave it at the screen that says EXITBS:START?

**Comment by robjvan** [comment]
I'm using an Intel AX200 wifi chip, could that be the issue...?

**Comment by mintphin** [comment]
After following all of this I still am unable to boot into it. Even worse, the picker doesn't want to start up.

**Comment by racka98** [comment]
> After following all of this I still am unable to boot into it. Even worse, the picker doesn't want to start up. 

What OS are you trying to boot?
And which Opencore version are you using?

**Comment by mintphin** [comment]
I tried Big Sur 11.4 and I'm using OpenCore 0.7.0.

**Comment by racka98** [comment]
If the picker doesn't show up that mean your BIOS settings are wrong.
Reset BIOS settings to default then set everything as recommended in README

**Comment by mintphin** [comment]
nvm i managed to fix it by using gibMacOS's boot image creator utility

**Comment by mintphin** [comment]
ok i tried to install opencore on the drive itself. after rebooting the bios doesn't detect anything related to it. i tried what you did but it didn't work. what could i try?

**Comment by racka98** [comment]
> ok i tried to install opencore on the drive itself. after rebooting the bios doesn't detect anything related to it. i tried what you did but it didn't work. what could i try?

Boot with usb drive and reset nvram then reboot to the internal drive (remove usb drive)

**Comment by mintphin** [comment]
Still having the same issue after doing so :/

**Comment by racka98** [comment]
Where did you place EFI files and how did you place them?

**Comment by mintphin** [comment]
I used EFIMount and copied the files inside the EFI folder in my Catalina flash drive to the partition.

**Comment by racka98** [comment]
> I used EFIMount and copied the files inside the EFI folder in my Catalina flash drive to the partition.

This is how it should be placed![efi-moved.87262fda.png](https://user-images.githubusercontent.com/41214249/122045130-067d9e00-cde6-11eb-8b26-ef31004c7c5f.png)

**Comment by mintphin** [comment]
Thank you! Fixed!
Also this repo is a fantastic job. Keep it up!

**Comment by itzmanish** [comment]
> nvm i managed to fix it by using gibMacOS's boot image creator utility

What was the problem? And what you did to fix it?

**Comment by nerdthatnoonelikes** [comment]
> 
> 
> **Describe the bug**
> After creating the boot thumbdrive with OpenCore.
> 
> **To Reproduce**
> I created the bootdrive using Ubuntu and followed the [first method](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#method-1). Afterwards, I copied the `BaseSystem.dmg` and the `BaseSystem.chunklist` (which I got via macrecovery.py for Big Sur; tried Catalina too, same result) to the `com.apple.recovery.boot` folder at the root of the drive. After that I downloaded the EFI folder from this repo and placed it along the `com.apple.recovery.boot` folder at the root.
> 
> Then I restarted the laptop, went into BIOS and changed all the options from the README.
> 
> When choosing the thumbdrive as a startup device, I was greeted with OpenCore screen with icons, where I clicked the first one. Then the screen went black (but lit up). Sometimes it stays this way for more than 20 minutes until I manually turn off the laptop, other times it just reboots randomly. I tried using DEBUG version of OpenCore in hopes of getting the logs and finding the problem but to no avail (I replaced the files from the EFI folder from this repo to the files from the DEBUG release, as stated [here](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps): everything stays the same, even if I delete `OpenCanopy.efi` and remove the lines for it from config.plist.
> 
> **Expected behavior**
> The installation starts.
> 
> **Hardware:**
> ThinkPad T450, i5-5300U, HD Graphics 5500, 8 GB, Intel 7265
> 
> **Additional context**
> I've noticed that the `config.plist` in the repo is capitalized, however it is not in the guides. Nonetheless, changing it (nor not changing it) doesn't help to solve the issue.
> 
> [The content of my drive (roor)](https://i.imgur.com/xJTNzH6.png)
> 
> [The content of my drive (EFI/OC folder)](https://i.imgur.com/a9PUodo.png)
> 
> I'd be happy to provide any additional info that might be required and if I install the MacOS successfully, I'd love to contribute to writing a detailed guide, if you want any help! Thanks in advance!

I have the same issue with my Thinkpad x250, i5-5300u. How did you make the USB with gibMacOS's boot image creator utility? I keep getting this error `InstallAssistant.pkg is not in the available recovery package names:
recoveryhdupdate.pkg, recoveryhdmetadmg.pkg`

**Comment by racka98** [comment]
Looks like a broken installer or the Installer package wasn't fully downloaded. Have you tried downloading it again?
