### ISSUE TITLE
OCB: StartImage failed - Aborted

### ISSUE THREAD

**Issue by Eratiug05** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#20]
Hi,
Thank you for this guide !
I succefully installed Big sur 11.2.1 on a T450 i5.
I reboot several times without key boot.
But this morning it didn't want to boot once selected the disk on GUI.

I got this
OCB: StartImage failed - Aborted

I tried to reset NVRAM, then the Recovery on GUI turned yellow. 
I replaced EFI. Still stuck.
I have downloaded stuffs from the appstore with my usual account. A mistake?
Anyway i'm a newbie french guy living in south alps. So i probably missed something :-) ?
I didn't have this issue with Catalina.

T450 
16 Go ram
500 SSD (BX500 crucial)

Thanks for help
![OCB statimage failed](https://user-images.githubusercontent.com/80333799/110511193-46a4f480-8104-11eb-8528-de974875487b.jpeg)

**Comment by Eratiug05** [comment]
No dual boot

**Comment by racka98** [comment]
Open config.plist and under Booter > Quirks set DevirtualiseMmio to True and report back if it fails to boot

**Comment by racka98** [comment]
Also what OC version are you on?

**Comment by Eratiug05** [comment]
I tried this yet. It didn't work. I can check again.
Intel HD Graphics 5500

**Comment by Eratiug05** [comment]
It still doesn't work.

[opencore-2021-03-09-165500.txt](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/files/6110527/opencore-2021-03-09-165500.txt)

**Comment by Eratiug05** [comment]
The last version of Opencore.
Humm..I didn't get a serial number. I tried to get a valid one but i was exhausted after 30 fails.
This point was not really clear for me. Didn't understand it's a must have.
My understanding of english (and hackintosh) is sometimes a bit tricky. Sorry.
It means i have to reinstall ?

**Comment by racka98** [comment]
You can try a reinstall. If you can't get a serial number via macSerial try Clover configurator. Just open clover configurator, navigate to the serial no section and generate serial number for MacBook Pro 12,1 and copy all the necessary stuff into their respective parts in Config.plist>PlatformInfo

**Comment by Eratiug05** [comment]
I get many serial number with mac serial but when i check in apple coverage they are not valid.
No need to have a valid serial number to copy in Platforminfo ?
I'll try a reinstall.

**Comment by racka98** [comment]
If they are not valid you are good to go. Use them

**Comment by Eratiug05** [comment]
Hello
So still the same.
Reinstall was ok. It did boot many times.
I get a serial number, i did the all stuff then checked with macserial. It seemed ok.
I briefly begun to download logic pro trial. That i stopped quickly. I didn't use any apple ID.
Then i decided to turn on file vault. I reboot to stuck on 
OCB: StartImage failed - Aborted
To devertualize mmio (on)  doesn't work.
I tried to up date open core (0.6.6 to 0.6.7) replacing only the main files. 
Any ideas?

**Comment by racka98** [comment]
I'm so sure if file vault actually works on this efi because i never tested this. File vault can indeed prevent you from booting if not setup properly in the efi. I suggest you don't use file vault unless you configure it properly in the efi

**Comment by racka98** [comment]
You can try fixing FileVault by following this [guide](https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html) here and see it will boot since there's no way to turn off file vault with the computer not booting to the OS

**Comment by Eratiug05** [comment]
It works ! 
I first change EFI to 0.6.6
I 'll try with 0.6.7
Thank you

**Comment by racka98** [comment]
You fixed FileVault?

**Comment by Eratiug05** [comment]
Yep 
thanks to this open core guide.
