### ISSUE TITLE
Can not reach installer with t450s

### ISSUE THREAD

**Issue by robjvan** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#21]
Tried following this guide with both Big Sur 11.0.1, 11.2.1, and Catalina 10.15.5 ISOs.  Tried using Kingston Ultimate and Sandisk Ultra USB3 drives.

Wiped the install USB with disk utility and did the createinstallmedia command each time. 

Then copied the custom EFI folder over to the clean EFI partition. 

It boots, but gets stuck immediately after boot at various errors regarding LOCHB or dmg.root_hash.  Tried using Intel 7265, 8260, and AX200 chips.  

Simply cannot make it work.

**Comment by robjvan** [comment]
Also tried Mojave - couldn't get that working either.

On the 700th try without any deviation from the standard steps as laid out in the guide, Big Sur 11.0.1 boot and I was able to get the installer started.  Unfortunately, I don't know what is different and made it work.

**Comment by racka98** [comment]
Did you try setting these in Booter -> Quirks section of config plist

EnableWriteUnprotector -> True
RebuildAppleMemoryMap -> False
SyncRuntimePermissions -> False
SetupVirtualMap -> True
DevirtualiseMmio -> False

**Comment by robjvan** [comment]
The only setting I had to change was "SyncRuntimePermissions", all the others were already set to those values.  Now it won't boot at all again, just reboots after a flash of an error.  I'm starting to question how badly I want macOS on my t450s.

**Comment by racka98** [comment]
BIOS settings? Have you tried restoring them to default then setting them up as recommended in the read.me?

**Comment by robjvan** [comment]
Yep, done that a few times.  This was a new replacement motherboard delivered today, so the settings have been cleared quite a few times (redundantly, lol)

**Comment by robjvan** [comment]
This might be a dumb question, but I can manipulate the EFI/config.plist on the USB, correct?  Or do I need to make the changes elsewhere (say the Downloads dir) then copy the EFI files over again each time?

**Comment by racka98** [comment]
Do you have the full log? Might be something weird going on

Also have you tried with older builds like 0.6.3?

**Comment by robjvan** [comment]
I was able to get more consistent boot success with 0.6.3, but the installer seems to reboot when the progress bar is halfway through.  At this point, I can boot using the USB but can't seem to continue the install process from the target HDD.  

I'm kind of an idiot, wasn't using a proper release version before - I had just downloaded a zip of the github code so I'll try Catalina or Mojave again but I'm not feeling confident at this point.  Not even sure wtf is going on.

**Comment by racka98** [comment]
> I was able to get more consistent boot success with 0.6.3, but the installer seems to reboot when the progress bar is halfway through.  At this point, I can boot using the USB but can't seem to continue the install process from the target HDD, as the system just reboots when I select the HDD in the USBs boot menu.
> 
> I'm kind of an idiot, wasn't using a proper release version before - I had just downloaded a zip of the github code so I'll try Catalina or Mojave again but I'm not feeling confident at this point.  Not even sure wtf is going on.  

Any error show up when it reboots? Is verbose mode turned on?
