### ISSUE TITLE
Unable to boot after manually updating to open core 0.6.9

### ISSUE THREAD

**Issue by Cxistiro** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#22]
So I am using your new EFI folder (open core 0.6.8) and it was working fine but then I saw that open core 0.6.9 released so I went ahead and updated all files, but then it would not boot anymore (It boots to a black screen with no options). And the problem is that I tried using your  open core 0.6.8 EFI folder and even that didn’t boot anymore (was working before).

**Comment by racka98** [comment]
> So I am using your new EFI folder (open core 0.6.8) and it was working fine but then I saw that open core 0.6.9 released so I went ahead and updated all files, but then it would not boot anymore (It boots to a black screen with no options). And the problem is that I tried using your  open core 0.6.8 EFI folder and even that didn’t boot anymore (was working before).

So it doesn't show you the boot options? Remember to also use the new config.plist and new resources folder.

Basically you have to replace the whole EFI with the new and add your PlatformInfo and any other changes you made from the old config.plist to the new one

**Comment by SaladXL** [comment]
Efi work in 0.6.9 for me but not 0.7.0? Idk why it not work for you in 0.6.9 what does it say - translate from rupa
