### ISSUE TITLE
Battery service recommended

### ISSUE THREAD

**Issue by notfrommalaysia** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#23]
Hi, I've done the installation. But one thing keep bugging me is that the 'Service Recommended' warning at the battery section and it seems that my t450s can only withstand 2 hrs of usage of battery while on windows it can stay longer. Did I skipped any steps or is it just normal? thanks!

![Screen Shot 2021-05-04 at 9 13 27 AM](https://user-images.githubusercontent.com/72158554/116970876-fe93ef80-acb8-11eb-84df-1fe48c8b850d.png)

**Comment by racka98** [comment]
How much longer does it actually stay on Windows? You'll obviously loose some battery life because macOS does not throttle you performance on battery like windows. I also have that warning since my batteries are pretty old but i still get 4 hrs of moderate usage. Use the coconut battery app to see how much health your batteries have

**Comment by notfrommalaysia** [comment]
I get around 4 hours on windows. So theres no workaround removing that warning sign? In before i used an x230 hackintosh and the same thing occur even when i just bought a new battery.

**Comment by racka98** [comment]
> I get around 4 hours on windows. So theres no workaround removing that warning sign? In before i used an x230 hackintosh and the same thing occur even when i just bought a new battery. 

Nope. The warning never showed up when my battery health was above 80%. Might have to do with dual batteries not being correctly reported. Have you tried turning it on with only 1 battery in?

**Comment by notfrommalaysia** [comment]
Already tried and the same issue persist. Nevermind then. 

Another problem i currently face is stuttering bluetooth audio. Do you currently have any solution for this? Thanks.

**Comment by racka98** [comment]
> Already tried and the same issue persist. Nevermind then. 
> 
> Another problem i currently face is stuttering bluetooth audio. Do you currently have any solution for this? Thanks. 

It's an issue with the Linux driver used by IntelBluetooth kext. Unless they fix it there's nothing much we can do
