### ISSUE TITLE
Broken in new update 0.7.0

### ISSUE THREAD

**Issue by SaladXL** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#25]
**Describe the bug**
Efi was working in opencore 0.6.8 and 0.6.9 but after updating to opencore 0.7.0 it only shows reset nvram

**To Reproduce**
Update to opencore 0.7.0 and not work

**Expected behavior**
I expected everything to work

**Screenshots**
N/A

**macOS Info:**
 - OS: Big Sur 11.4 BETA 2
 - Laptop Model: T450

**Additional context**
Not sure why it doesn’t work in 0.7.0 because I manually updated to 0.6.9 and it worked

**Comment by racka98** [comment]
I haven't tried 0.7.0 so i don't know what's wrong. You can try reading the changelog to know what needs to be changed for it to work. I generally don't update frequently unless i really need to.

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
