### ISSUE TITLE
Change in the documents

### ISSUE THREAD

**Issue by rwillett** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#27]
**Is your feature request related to a problem? Please describe.**
Step 9. in the instructions on what to copy into the EFI folder could be better explained.

**Describe the solution you'd like**
Instead of "Copy the OC and BOOT files from my EFI and fireup the installer." 

It might be better to say "Copy the EFI Folder with sub folders OC and BOOT files from my EFI folder. to the EFI drive. This means that the EFI folder is at the root of the EFI drive with two sub folders.".

A second line would then be

"Restart the laptop with the USB key and select the 'Install  Big Sur option" rather than "fireup the imstaller"

Apart from that mistake I made (twice), it worked well.

Thanks

Rob

**Comment by racka98** [comment]
Noted
