### ISSUE TITLE
Change documents 

### ISSUE THREAD

**Issue by Cxistiro** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#28]
Is your feature request related to a problem? Please describe.

no

Describe the solution you'd like

In the guide it saids you can’t make the bootable drive in windows or Linux but I tried making it in windows today following the open core guide using macrecovery (big sur)and it worked.

**Comment by Cxistiro** [comment]
I actually prefer the online installer because it’s faster since you don’t have to flash it to your external flash drive. Also it’s nice to have the USB stick ready so fast because u can just leave ur pc on and do other stuff but if you used offline you would have to wait for it finish flashing the USB then boot into the installer and stuff

**Comment by racka98** [comment]
I haven't updated the guide in a very long time. It didn't work when Big Sur was out. I'll update the guide when i get the time. 

You can also edit the readme and issue a pull request. I've been really busy and haven't gotten any time to update stuff

**Comment by Cxistiro** [comment]
ok I'm issuing a pull request now thanks

**Comment by racka98** [comment]
Did you update to macOS 12 on the Thinkpad?

**Comment by Cxistiro** [comment]
Yes I wrote this guide because I made the hackintosh for my brother and I
can’t ask for his computer to take a screenshot because it’s midnight but I
did it for fun

**Comment by Cxistiro** [comment]
Writing this in the email glitched it out

**Comment by racka98** [comment]
> Yes I wrote this guide because I made the hackintosh for my brother and I
> can’t ask for his computer to take a screenshot because it’s midnight but I
> did it for fun
> 

With 0.6.8?

**Comment by Cxistiro** [comment]
Yes

**Comment by racka98** [comment]
Ok. I've merged the changes.
