### ISSUE TITLE
Mouse input killed after waking from sleep Catalina

### ISSUE THREAD

**Issue by unresolvedsymbol** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#3]
**Describe the bug**
Trackpad and trackpoint aren't working after resuming on Catalina, even without Airportitlwm IntelBluetooth or even itlwm kexts loaded. Does the latest commit support Catalina still? This doesn't happen on echospirits opencore configuration albeit severely outdated.

**To Reproduce**
1. Sleep
2. Wake up the laptop

**Expected behavior**
Trackpad and trackpoint should work after resuming from sleep

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7

**Comment by racka98** [comment]
That Is weird. It was working on Catalina. I updated this EFI to Big Sur while still dual booting Catalina. I checked if everything was working in Catalina too. Can you check if this happens on the older Catalina releases I published a while a go. [Here](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/releases/tag/Cat-BigS-OC-0.6.3)

**Comment by unresolvedsymbol** [comment]
I tried the release linked and even the first release that only mentioned catalina, no dice. Yes I have WoL and fingerprint reader device access disabled (my SKU doesn't even have the fingerprint reader anyway, only i7 and 1080p touchscreen.) USB mice do still work after resuming, just neither of the internals.

**Comment by racka98** [comment]
> I tried the release linked and even the first release that only mentioned catalina, no dice. Yes I have WoL and fingerprint reader device access disabled (my SKU doesn't even have the fingerprint reader anyway, only i7 and 1080p touchscreen.) USB mice do still work after resuming, just neither of the internals.

Did you install the touchscreen kext??

**Comment by unresolvedsymbol** [comment]
No, I'm not worried about touchscreen input. I usually use tiling wms anyway lol. It shouldn't be an issue since the touchscreen device is connected via an internal USB hub, should it?

**Comment by unresolvedsymbol** [comment]
Looks like the issue is with VoodooRMI, I switched back to VoodooPS2Trackpad and now the trackpad still works after resuming from full sleep (fading light)

**Comment by racka98** [comment]
> Looks like the issue is with VoodooRMI, I switched back to VoodooPS2Trackpad and now the trackpad still works after resuming from full sleep (fading light)

Yeah VoodooRMI is the probability the culprit. It just better that's why i use but it seems to have issues with other smbus/ps2 devices

**Comment by unresolvedsymbol** [comment]
Which kext is responsible for the trackpoint? I disabled VoodooTrackpoint (it still didn't work with this one enabled) and added VoodooPS2Mouse but it doesn't seem to work at all now.

**Comment by racka98** [comment]
I was using VoodooTrackpoint inside of VoodooRMI/Contents/PlugIns
