### ISSUE TITLE
Thanks it works but very slow boot

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#34]
Hello thank you so much for the amazing guide and efi I got macOS Monterey installed successfully on my thinkpad t450s using this efi but it takes a long time to boot any solutions?

**Comment by theadamtube** [comment]
Fixed it! Just a 3 minute google search :D

**Comment by theadamtube** [comment]
Very easy fix

**Comment by racka98** [comment]
> Very easy fix

What was the issue?

**Comment by theadamtube** [comment]
The kext I had to add some boot args and update some kext value but it works perfectly now! Thank you it boots around 28 second now. Sorry English is not my native language

**Comment by racka98** [comment]
> The kext I had to add some boot args and update some kext value but it works perfectly now! Thank you it boots around 28 second now. 

What kext exactly you had to add and which boot-args? I want to fix it so no one else will face the same issue.

> Sorry English is not my native language 

No problem. English is not my native language either

**Comment by theadamtube** [comment]
-lilubetaall And also some beta flag

**Comment by theadamtube** [comment]
Also Bluetooth does not currently work in Monterey but it will probably be fix in a few day short time anyway

**Comment by theadamtube** [comment]
Other then Bluetooth all working

**Comment by theadamtube** [comment]
Also I updated some kext which is super fast 1 minute

**Comment by racka98** [comment]
Ok. I'll pin this so when others have the same issue can see the solution

**Comment by itzmanish** [comment]
@theadamtube which kexts specifically?
