### ISSUE TITLE
Monterey Bug

### ISSUE THREAD

**Issue by Oliwier-dev** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#35]
**Describe the bug**

**Expected behavior**
The system does not start, it tries to turn on bluetoothd without semaphore forever

**macOS Info:**
 - OS: Monterey
 - Version 12
 - Laptop Model: T450

**Comment by Cxistiro** [comment]
wait for the developer of the blue tooth kext to update it for macOS Monterey it is not supported (yet). also to boot u need to add some boot args and kext

**Comment by racka98** [comment]
I haven't actually installed macOS 12 on my laptop yet. So any bug you encounter right now you'll have to look around to fix it

**Comment by racka98** [comment]
Use the new EFI it doesn't need any changes to boot
