### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#36]
Hello sir thank you for the open core update 
**Describe the bug**
There is no sound from built in speaker 
**To Reproduce**
1. Boot macos
2. Play audio

**Expected behavior**
I expected to hear sound 

**Screenshots**
N/A

**macOS Info:**
 - OS: Monterey
 - Version 12.0
 - Laptop Model: T450
**Additional context**

**Comment by racka98** [comment]
Have you followed the post install for alc? There's a new alc_fix, try installing it

**Comment by theadamtube** [comment]
Was using an external keyboard, didn’t notice mute button was enabled on built in keyboard

**Comment by racka98** [comment]
> Was using an external keyboard, didn’t notice mute button was enabled on built in keyboard 

Ok no problem. Are there any other bugs?

Also report back if you loose sound after putting the laptop to sleep for a long time.
I have disabled the codeccommander kext in favor of a new layout id and new alc_fix.

**Comment by theadamtube** [comment]
Not that I know if thank you
