### ISSUE TITLE
Sound 22

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#37]
**Describe the bug**
Sound works on big sur but not Monterey 
**To Reproduce**
1. Boot macOS
2. Play audio

**Expected behavior**
I expected to have audio feedback

**Screenshots**
Nan

**macOS Info:**
 - OS: Monterey 
 - Version 12
 - Laptop Model: t450

**Comment by racka98** [comment]
Try turning on Codeccommander.kexy inside config.plist

**Comment by theadamtube** [comment]
Going to try it now 👍

**Comment by theadamtube** [comment]
Worked like a charm thank you

**Comment by racka98** [comment]
> Worked like a charm thank you

No problem. I'll turn it on too since it seems to still affect Monterey users
