### ISSUE TITLE
Monterey very slow

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#38]
**Describe the bug**
The operating system feels very slow overall

**To Reproduce**
For example,
1. Try launching any application like finder for example
2. Start dragging the window arround and u will feel a ton of lag

**Expected behavior**
A smooth 60 FPS experience just like big sur

**Screenshots**
Nan

**macOS Info:**
 - OS: Monterey 
 - Version 12
 - Laptop Model: t450

**Additional context**

**Comment by theadamtube** [comment]
I noticed it was only slow because the GitHub home page was in the background but this didn’t happen on big sur still anybody know why performance dropped a lot

**Comment by theadamtube** [comment]
Dragging brightness, sound sliders in control panel are very noticeably laggy too

**Comment by theadamtube** [comment]
The system even fails to complete simple tasks quick like opening some of the options in system preferences can take up to 8/9 seconds and even close system preferences can sometimes take 4 seconds

**Comment by racka98** [comment]
Hhm I don't know about that. Might be a macOS thing. Remember that Monterey is still in it's first beta and you shouldn't depend on it to work perfectly. 

Did this happen on OC 0.6.8?

**Comment by theadamtube** [comment]
Yes

**Comment by theadamtube** [comment]
After using it for the past hour, things have sped up
