### ISSUE TITLE
Prompts to setup keyboard every boot

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#39]
**Describe the bug**
Every time you boot the laptop it prompts you up to setup an external keyboard. This isn’t too big of a deal but it is kind of annoying in a small way

**To Reproduce**
1. Have a external keyboard plug in
2. Boot macOS 

**Expected behavior**
I expected a boot without the keyboard setup prompt

**Screenshots**
Nan

**macOS Info:**
 - OS: Monterey 
 - Version 12
 - Laptop Model: t450

**Additional context**
I’m not 100% sure if it is a macOS bug but it doesn’t happen on my m1 macbook. So it may be the hackintosh

**Comment by racka98** [comment]
This is just a macOS thing. It does that for external keyboard when NVRAM is reset or when you change the opencore version
