### ISSUE TITLE
Wake from Sleep issues on Catalina

### ISSUE THREAD

**Issue by batman38102** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#4]
If I leave my T450

**Comment by batman38102** [comment]
Sorry accidentally clicked to post before finishing.

**Describe the bug** 

Closing the lid or the laptop going to sleep and then trying to wake up the laptop causes the display to be black on Mac OS Catalina. 

**To Reproduce Steps to reproduce the behavior:**

Close the lid or wait for the laptop to go to sleep. Try to wake up the laptop and it should have a black screen.


**Expected behavior**

Laptop should wake up and the display should be on and working. 

**Hardware**

T450

**Comment by batman38102** [comment]
Please let me know if I have missed anything in regards to the format

**Comment by batman38102** [comment]
Solved after doing Post Install steps outlined in README

**Comment by batman38102** [comment]
Spoke too soon. I am not sure why is this happening.

**Comment by batman38102** [comment]
If i leave the laptop for more than 5-10mins it refuses to wake up.

**Comment by racka98** [comment]
> If i leave the laptop for more than 5-10mins it refuses to wake up.

1. Make sure you turn off wake on lan and fingerprint scanner in bios.

2. Send the output of `pmset -g` from terminal

3. Did you edit anything in the config.plist or deleted any file included in EFI folder?

4. Are you on the latest EFI cloned from the repo? I updated it like 2 days ago and haven't tested if everything work in Catalina

**Comment by batman38102** [comment]
Unfortunately I have moved to Big Sur so I cannot do these things anymore. I am hoping it works better. I don't need to do all that in Big Sur do I?

**Comment by racka98** [comment]
> Unfortunately I have moved to Big Sur so I cannot do these things anymore. I am hoping it works better. I don't need to do all that in Big Sur do I?

You have to disable those two settings i bios. And make sure you are using the updated EFI
