### ISSUE TITLE
Yoga smc app errors

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#40]
**Describe the bug**
Yogasmc reports ec access is unavailable 
**To Reproduce**
1. Download yoga smc release app
2. Run it

**Expected behavior**
I expected the app to launch properly

**Screenshots**
Not right now 

**macOS Info:**
 - OS: big sur
 - Version: 11.4
 - Laptop Model: t450

**Additional context**
also if you click the yoga smc icon on the top bar and click preferences it will show failed to open system preferences

**Comment by theadamtube** [comment]
Also sorry for opening so many issue tickets not sure if I show type them all in one or what

**Comment by racka98** [comment]
Did you install the preference pane inside the YogaSMC dmg?

**Comment by theadamtube** [comment]
Yes I’ve installed them it said a ec access is not available

**Comment by theadamtube** [comment]
Btw for one key hidpi what do you recommend

**Comment by racka98** [comment]
> Yes I’ve installed them it said a ec access is not available 

Just ignore that. I didn't want to give it EC access because it can already do most of the stuff perfectly fine

**Comment by theadamtube** [comment]
Ok thank you what should I set for one key hidpi

**Comment by racka98** [comment]
> Ok thank you what should I set for one key hidpi

If you are using the 1366x768 display don't bother.

If you have a 1080p display and you feel like the current scaling is too small then you can use it. This will increase CPU usage of the Window manager process and can possibly impact performance if you have a lot of app windows open
