### ISSUE TITLE
Bluetooth fix 

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#41]
**Is your feature request related to a problem? Please describe.**
Yes, there is a way to get intel Bluetooth working in Monterey.
A clear and concise description of what the problem is. Bluetooth doesn’t work in Monterey 

**Describe the solution you'd like**
I found this solution in the issues section of the intel Bluetooth repository.
“ Looks like the latest firmware update in commit c52425f is not working properly in macOS Monterey. By reverting the firmware to its previous version, it is working on my setup.

To make Intel Bluetooth working in Monterey, following are needed:

Latest version of Lilu (from source)
Latest version of BrcmPatchRAM (from source), only need BlueToolFixup.kext in this package
IntelBluetoothFirmware.kext with older firmware (Can be built from https://github.com/pigworlds/IntelBluetoothFirmware/tree/revertfw)
IntelBluetoolInjector.kext is not needed.
Shutdown and restart machine instead of reboot.
Tested on Wireless-AC 8265 and Wireless-AC 9560 with streaming audio to Bluetooth headset.”

A clear and concise description of what you want to happen. Fix Bluetooth 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by racka98** [comment]
That's a workaround. I'll wait for the Intel Bluetooth kexts for Monterey to add them to the repo. You can use that workaround if you want. Using that workaround will probably break compatibility on with previous macOS versions
