### ISSUE TITLE
The Bluetooth kext support Monterey officially 

### ISSUE THREAD

**Issue by theadamtube** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#42]
All in title

**Comment by racka98** [comment]
Ok will add it later

**Comment by fearlipe** [comment]
Is there a chance to upload to monterey natively by just downloading/upgrading via system update when it launch?

**Comment by racka98** [comment]
Should be possible with the latest OC version

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
