### ISSUE TITLE
Static noise issues even after installing alc_fix_new

### ISSUE THREAD

**Issue by mintphin** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#43]
**Describe the bug**
After installing the fix I still suffer from the same issue

**To Reproduce**
1. Install Big Sur 11.4
2. Install alc_fix_new
3. Plug in the headphone jack
4. Noise

**Expected behavior**
Headphones shouldn't play any noise.

**macOS Info:**
 - OS: Big Sur
 - Version 11.4
 - Laptop Model: T450

**Additional context**
I tried putting my computer to sleep and waking from it but I still had the same issue.

**Comment by theadamtube** [comment]
Try enabling codec commander and doing the sleep method

**Comment by theadamtube** [comment]
Also plug in headphones before closing lid then after plugged in close and wait line 3seconds and open again

**Comment by mintphin** [comment]
Ok. It worked. Thanks!
