### ISSUE TITLE
Touchscreen IPS support

### ISSUE THREAD

**Issue by banks047** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#44]
**Is your feature request related to a problem? Please describe.**
Toucscreen not working

**Describe the solution you'd like**
Touchscreen working

**Describe alternatives you've considered**
I can see that [this](https://github.com/dimka4996/Thinkpad-x250-Catalina-Big-sur-opencore) person managed to achieve touchscreen support but i'm not sure how they've done that.

**Additional context**
It would be great if this feature could be added because this EFI is more up to date and could possibly enable touchscreen support on Monterey in the future as well. 

Let me know if you need more info.

**Comment by set-power007** [comment]
> **Is your feature request related to a problem? Please describe.**
> Toucscreen not working
> 
> **Describe the solution you'd like**
> Touchscreen working
> 
> **Describe alternatives you've considered**
> I can see that [this](https://github.com/dimka4996/Thinkpad-x250-Catalina-Big-sur-opencore) person managed to achieve touchscreen support but i'm not sure how they've done that.
> 
> **Additional context**
> It would be great if this feature could be added because this EFI is more up to date and could possibly enable touchscreen support on Monterey in the future as well.
> 
> Let me know if you need more info.

You are talking about the clay warehouse next door, the perfect black hackintosh.
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore

**Comment by racka98** [comment]
Working on it

**Comment by itzmanish** [comment]
Any status on touch support?

**Comment by racka98** [comment]
I've been very busy lately. You can see I haven't even updated the EFI to the latest version

**Comment by itzmanish** [comment]
Yeah. That's true. Any ETA or when you will be free?

**Comment by racka98** [comment]
I expect to update the EFI this month together with some fixes

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
