### ISSUE TITLE
Sleep/wake not working

### ISSUE THREAD

**Issue by tbilic14** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#45]
**Describe the bug**

**To Reproduce**
Laptop goes to sleep and does not wake up. Keyboard lights light up but screen stays blank.

**Expected behavior**
Screen should power up.

**Screenshots**

**macOS Info:**
 - OS: Big Sur 
 - Version 11.4
 - Laptop Model: T450

**Additional context**
Installed normal using the guide. Latest EFI used, no addidional changes done other then Postinstall #1
One thing maybe, I am unable to update BIOS to latest version via usb boot cd iso. "Secure authetification failed" message appears. I did all things found by googling but no luck still.

**Comment by racka98** [comment]
Try updating via Windows. The patched DSDTs are patched based on the latest BIOS version

**Comment by tbilic14** [comment]
> Try updating via Windows. The patched DSDTs are patched based on the latest BIOS version

Tried that also. Manually, via Lenovo updater... just out of ideas... :(

**Comment by tbilic14** [comment]
Also sometimes when trying to wake, laptop reboots.

**Comment by tbilic14** [comment]
I just realized that my BIOS version is JBET54WW (1.19), while EC version is 1.04. As I understand these two are bundled, and on lenovo download section for BIOS it says that the 1.02 version of EC is bundled with JBET54WW. Does anyone have an idea how can that be?

**Comment by racka98** [comment]
Do you use an External monitor?

Do you the Intel Wifi card or Broadcom?

Do you happen to have anything peripherals connected?

Do you have Ethernet connected when this happens?

For BIOS update try Resetting it to default settings then turn off Rollback prevention. Sometimes it thinks it's on the latest version and refuses all updates. 

Also check if there's any computrace Settings turned on. That can prevent BIOS updates if it was previously set up by corporate IT

**Comment by tbilic14** [comment]
> Do you use an External monitor?
No. I tried once hooking it with DP and DVI cable via docking station and it didn't work. Didn't investigate further still.

> Do you have the Intel Wifi card or Broadcom?
Intel. Works like a charm with airport for Big Sur.

> Do you happen to have any peripherals connected?
Usually no. Maybe just usb stick but same outcome with or without.

> Do you have Ethernet connected when this happens?
No.

> Also turn off Wake ON LAN in the BIOS and in macOS settings
Also did turn off.

> For BIOS update try Resetting it to default settings then turn off Rollback prevention. Sometimes it thinks it's on the latest version and refuses all updates.
This I found by googling, didn't help.

> Also check if there's any computrace Settings turned on. That can prevent BIOS updates if it was previously set up by corporate IT
Actually this is my old corporate laptop, I'll check that once more...

**Comment by tbilic14** [comment]
> Also check if there's any computrace Settings turned on. That can prevent BIOS updates if it was previously set up by corporate IT

I've set it to Permanently disabled. Didn't work. :(

**Comment by racka98** [comment]
You'll have to find a way to update the bios. There's an ssdt patch in this EFI that fixes sleep/wake issues so it's probably not working on old BIOS versions

**Comment by tbilic14** [comment]
> You'll have to find a way to update the bios. There's an ssdt patch in this EFI that fixes sleep/wake issues so it's probably not working on old BIOS versions

Went back to windows to try with flash utility. When going to an older firmware, only the EC get flashed. I noticed after the flash process two text files appear  in the flash utility folder (attached). One say flash process was successful (but I still have the same bios version) and the other one something about drive G: not available... Any idea what that could mean?
[null.txt](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/files/6734506/null.txt)
[Winuptp.log](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/files/6734508/Winuptp.log)

**Comment by racka98** [comment]
The first files has something to do with BitLocker. Do you have it enabled?

Also does it reboot when it says successful?

**Comment by tbilic14** [comment]
I disabled bitlocker.
I start flash program, laptop reboots, it should boot to bios flash but it
just says Secure Authentification Failed. After 10-15 sec, it shuts down.

**Comment by racka98** [comment]
There's definitely some restrictions put in by the IT who previously managed that laptop

**Comment by tbilic14** [comment]
Seems so…
Funny thing though, when I try to downgrade, ECP gets flashed to lower
version. It happens with the first boot after ‘secure flash
authentification’ message.

**Comment by tbilic14** [comment]
Just realized same thing with sleep/wake happens in win10 to!

**Comment by racka98** [comment]
Then it's definitely a BIOS issue.

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
