### ISSUE TITLE
Does this support high sierra?

### ISSUE THREAD

**Issue by Cxistiro** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#46]
does this support high sierra? and if it doesnt can you add support for it?

**Comment by racka98** [comment]
I can't add support for me because i haven't ever installed High Sierra on my machine. It's shouldn't hard to make it work on High Sierra for you. Probably just need to change a couple of settings in config.plist

**Comment by Cxistiro** [comment]
thanks! it worked without changing anything
