### ISSUE TITLE
Audio static noise after playing something

### ISSUE THREAD

**Issue by itzmanish** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#47]
**Describe the bug**
However somehow I get no noise after sleeping laptop for 3 second and again connecting headphone. But when I play something (tried with YouTube) I get static noise along with playing audio.

**To Reproduce**
1. Apply alc_fix
2. close the lid with headphone plugged in.
3. wake up from sleep after waiting 3 second.
4. play anything and get the noise

**Expected behavior**
There should be no noise even if audio is playing or not.

**macOS Info:**
 - OS: Big Sur
 - Version 11.4
 - Laptop Model:  T450s

**Additional context**
tried fix on #18 #37 .

**Comment by Cxistiro** [comment]
try with opencore 0.6.8

**Comment by racka98** [comment]
This is an issue with the codec support of alc. The codec in T450 & T440 (all variants) isn't fully supported by alc. The workarounds sometimes fail.

**Comment by itzmanish** [comment]
>> he workarounds sometimes fail.
Yes. It seem so.
>> The codec in T450 & T440 (all variants) isn't fully supported by alc. 
Mine is T450s.

Good news is it is working now. But still have to close the lid 😞 .
