### ISSUE TITLE
Cpu fan not working

### ISSUE THREAD

**Issue by itzmanish** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#48]
**Describe the bug**
After installing BigSur I found that cpu fan never runs which causes laptop to restart frequently.

**To Reproduce**
Follow the guide, install bigsur and use the efi from this repo without any modifications.

**Expected behavior**
CPU fan should run when temperatures rises.

**macOS Info:**
 - OS: Big Sur
 - Version: 11.0.4
 - Laptop Model: T450s

**Comment by racka98** [comment]
Does the fan spin when you booting the laptop or in Windows?

**Comment by itzmanish** [comment]
yes. It was working fine before on ubuntu.

**Comment by racka98** [comment]
Does it work now in Ubuntu? Or when you are powering ON the laptop?

**Comment by itzmanish** [comment]
Now I don't have ubuntu so I can't say. But when I power ON the laptop it runs.

**Comment by racka98** [comment]
Check if TempToFans.SSDT is enabled in Config.plist and also install the Thinkpad Assistant app as described by the README

**Comment by itzmanish** [comment]
TempToFans.SSDT is enabled and also yogaSMCNC and ThinkPad Assistant both are installed and running on login. When I try to enable fan control in yoga SMCNC a popup comes with Ec is unavailable.

**Comment by itzmanish** [comment]
I don't know how but I installed smcFancontrol app and after modifying and reverting settings now fans are running after cpu reaching 55°C.

**Comment by itzmanish** [comment]
And I see max cpu temp on running 4k video on YouTube is 78°C. Is it good or bad?

**Comment by racka98** [comment]
That probably means your fan isn't working as it should. I suggest you test it with another OS. Like just a Linux distro from a USB drive to see if the fans are working as they should.

**Comment by itzmanish** [comment]
Ok. Have you or anyone else saw restarting unexpectedly sometime?

**Comment by racka98** [comment]
> Ok. Have you or anyone else saw restarting unexpectedly sometime? 

Maybe after a very long sleep. Like if I leave the laptop for about 2 days

**Comment by itzmanish** [comment]
Not on sleep. On zoom call I experienced this

**Comment by racka98** [comment]
That doesn't happen on mine. However T450/T450s have an issue with the second RAM slot becoming loose. This means on of the RAM jiggles inside the slot and this causes the laptop to freeze and shutdown/reboot. Check this by removing 1 RAM at a time to determine if you have loose RAM slot

**Comment by itzmanish** [comment]
That can be issue because I am using second RAM slot.
