### ISSUE TITLE
Noise on Jack

### ISSUE THREAD

**Issue by nhd0** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#49]
hi, thank you for your work, everything was good, but I'm in trouble with jack noise, that can't be fixed with 8th step on post install, just try 3 times and can't solve this.  disable codeccommander.kext not solve it too, the only solution just use old method with manually sleep and wake.... thank you

**Comment by racka98** [comment]
The workaround seems to be broken again. So the only fix is the sleep wake trick

**Comment by nhd0** [comment]
yes only sleep wake trick,

**Comment by pentium0** [comment]
I found a fix that worked for me, on Big Sur 11.2.3 on my T450.
The newalcportfix didn't work and i still had noise, as others have reported.
What I did:
1) I removed the install of the newalcportfix (included in this repo), including the /Library/LaunchAgents/com.dark-dragon.....plist
2) Applied the alcfix from this thread:
https://www.tonymacx86.com/threads/opencore-mojave-installation-on-lenovo-thinkpad-t450-howto-fix-audio-problem.303545/
3) Enabled codeccommander in config.plist (changed enabled=0 to enabled=1)

[T450-ALCPlugFix.zip](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/files/6898507/T450-ALCPlugFix.zip)

**Comment by racka98** [comment]
Thanks. I'll test it then add it to the repo

**Comment by cchyswy** [comment]
I also fix the noise of the earphone with CLAY, install the BIG SUR after installing the BIG SUR, and the headphone noise problem is solved.

There is also the latest driver of DW1820A, don't need to be injected, this can be updated.

**Comment by fearlipe** [comment]
> I also fix the noise of the earphone with CLAY, install the BIG SUR after installing the BIG SUR, and the headphone noise problem is solved.
> 
> There is also the latest driver of DW1820A, don't need to be injected, this can be updated.

About the earphone, is there any guide?

**Comment by cchyswy** [comment]
> > I also fix the noise of the earphone with CLAY, install the BIG SUR after installing the BIG SUR, and the headphone noise problem is solved.
> > There is also the latest driver of DW1820A, don't need to be injected, this can be updated.
> 
> About the earphone, is there any guide?

https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/tree/master/ALCPlugFix

Refer to this, I am using this patch now.

Sorry, the previous mistake, is installed after installing BIG SUR, install this patch, the headset noise problem is solved.

**Comment by fearlipe** [comment]
Din't work here, just executed the install.sh and restarted: same noise on headphone jack.

**Comment by cchyswy** [comment]
Don't need other operations, you can perform the installation script.
CodecCommander.kext needs to be loaded in config
Or try RESET NVRAM

**Comment by fearlipe** [comment]
Ok, i've enabled the codeccommander and now it does not boot, says : missing injected kext... now I don't have another pc D:

**Comment by fearlipe** [comment]
Ok, solved it! I was lucky to heave a backup flashdrive with the default EFI init! I've added the missing kext to the folder and the headphone jack it's working fine now!

**Comment by Heart-Hacker786** [comment]
HI there i used this guide and made myself a catalina working hackinstosh and then upgraded to big sur through the install big sur app.
now i am having no audio at all

**Comment by Heart-Hacker786** [comment]
> > > I also fix the noise of the earphone with CLAY, install the BIG SUR after installing the BIG SUR, and the headphone noise problem is solved.
> > > There is also the latest driver of DW1820A, don't need to be injected, this can be updated.
> > 
> > 
> > About the earphone, is there any guide?
> 
> https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/tree/master/ALCPlugFix
> 
> Refer to this, I am using this patch now.
> 
> Sorry, the previous mistake, is installed after installing BIG SUR, install this patch, the headset noise problem is solved.

Thanks Bro i used this install.sh and enabled codexcommander in cofig and now i am good
