### ISSUE TITLE
can you please make a hackintosh guide of t450s with intel i5-6200u (actually I had upgraded the hardware)?                                                                                          following are the hardware specifications:                                      i5-6200U                 intel hd graphics 520                

### ISSUE THREAD

**Issue by TechPsychotic** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by racka98** [comment]
I don't have that model so I can't really make an EFI for it. That will involve changing a lot of stuff in the config.plist. Maybe you could try a T460 efi since it has that processor

**Comment by TechPsychotic** [comment]
and can i use the same ktexts?

**Comment by racka98** [comment]
The kexts should mostly be the same

**Comment by TechPsychotic** [comment]
ok
