### ISSUE TITLE
unable to login to facetime/imessage/icloud

### ISSUE THREAD

**Issue by iAlcatrazZ** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#51]
After updating the config.plist file following the guide on dortania github and restart, I still can't login to facetime, imessage and icloud. I've tried many times and I'm on Big Sur 11.5

**Comment by racka98** [comment]
Your email is probably blacklisted by Apple. Follow these steps: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by iAlcatrazZ** [comment]
Hi, thanks you for replying, I believe my account is not yet blacklist since I can still use it on my iphone and ipad, I did follow the instruction by Dortania and I have tried quite some times actually

**Comment by racka98** [comment]
> Hi, thanks you for replying, I believe my account is not yet blacklist since I can still use it on my iphone and ipad, I did follow the instruction by Dortania and I have tried quite some times actually

It just gets blacklisted for registration on that device not all other devices. If it says call Apple then it is definitely blacklisted and you are supposed to call Apple

**Comment by iAlcatrazZ** [comment]
thanks bro, I'll try again with new serial numbers

**Comment by racka98** [comment]
New serial numbers should be ok. But if it says contact Apple then the only way to get it working is changing the email or contacting Apple
