### ISSUE TITLE
m.2 ssd is working?

### ISSUE THREAD

**Issue by fearlipe** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#52]
I'm planning on getting a m.2 ssd for the t450, is it working (having a m.2ssd and sata ssd at the same time)?

**Comment by Cxistiro** [comment]
sergio scar

**Comment by tahmid-H** [comment]
Yes. I currently have an m.2 and sata ssd plugged in. m.2 has Big Sur, and sata ssd has Windows 10. Works fine.

**Comment by fearlipe** [comment]
Nice! Thanks!
