### ISSUE TITLE
Big Sur 11.5.2 working?

### ISSUE THREAD

**Issue by fearlipe** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#53]
Is it safe to auto update to 11.5.2 that apple just released?

**Comment by shrikantbhat** [comment]
Yes. i have updated and it is working fine.

**Comment by fearlipe** [comment]
Do you have the intel wifi? Headphone jack fix?

**Comment by shrikantbhat** [comment]
Intel wifi is working , headphone jack is not yet fixed - sleep it and wake it up to temporarily remove static noise

**Comment by fearlipe** [comment]
I just updated and it is indeed working fine with 11.5.2.

Also, I've used the method that is in another issue to solve de headphone jack issue and its also working fine.

**Comment by Dynasty-Dev** [comment]
What method got your headphone jack working?

**Comment by fearlipe** [comment]
Take a look here: https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore/issues/49

And please, be careful when dealing with these changes, always keep a EFI boot drive available to avoid losing your installation.
