### ISSUE TITLE
Can this guide be used for i7-5600U CPU?

### ISSUE THREAD

**Issue by jonasandero** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#54]
I am just a happy user and not an Hackintosh expert, so I wonder if you could comment on if this guide would apply to my hardware (i7-5600U an d Intel HD 5500 graphics)?

**Comment by Dynasty-Dev** [comment]
Hello, jona! Yes, your ThinkPad model is supported.

**Comment by racka98** [comment]
Yes. The CPU is supported
