### ISSUE TITLE
Thank you, Monterey is awesome!

### ISSUE THREAD

**Issue by Dynasty-Dev** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#57]
Just wanted to say thank you for the acpi, I made my own efi with updated open core 0.7.3 and all kext updated and copied you acpi and renames and it works great! thank you, the system boots up fast (20 second) and everything is working, even bluetooth toggle on and off with BlueToolFixup.kext and IntelBluetoothFirmware.kext 2.0 turn off intelbluetoothinjector in kernel > add. 
![Screen Shot 2021-08-26 at 7 00 20 PM](https://user-images.githubusercontent.com/89283708/131046987-4462ed05-b3fa-4944-97e0-c1b0bae690ff.png)

**Comment by lukasdk6** [comment]
Hello @Dynasty-Dev, 

How u doing?

How about the DRM in Monterey? 

The Apple TV or Music (Dolby/Lossless) works?

Regards,

**Comment by V3ntus** [comment]
Thanks a bunch for sharing!
