### ISSUE TITLE
Battery Options grayed out

### ISSUE THREAD

**Issue by ScrewedDriver** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#58]
With the help of your repo and the guide i successfully installed BigSur on a Thinkpad T450.

My problem is, that i can't change any options in the Battery Preferences.
Did I miss something?

**Comment by fearlipe** [comment]
Maybe incorrect bios settings?

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
