### ISSUE TITLE
Cant pass this screen after change wifi card

### ISSUE THREAD

**Issue by notfrommalaysia** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#60]
Hi, i changed my wifi card to bcm94360cs2 with adapter and with that i cant pass this screen. This screen appears when i select install mac os big sur. I use your efi config. Please advise, thank you very much. Attached are the error shown and wifi card. 
![7E53C11F-67AF-4049-83AE-324A40224432](https://user-images.githubusercontent.com/72158554/133617672-3bacdd33-6c5f-4ce7-a4d4-2137d1b1c4e3.jpeg)
![7572F01B-22F5-4319-9B65-C10AE6960C90](https://user-images.githubusercontent.com/72158554/133617716-cc00caa5-313f-4f98-912e-6ad9360bcadd.jpeg)

**Comment by racka98** [comment]
I have never used that card so I can't really help you. Sorry! Try checking the error on forums. This is out of the scope of this repo
