### ISSUE TITLE
Crash after find an update

### ISSUE THREAD

**Issue by Mielisi** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#61]
**Describe the bug**
After find any update from the appstore or the system preferances the system keep crashing after 5/10 minutes, after reboot it give me a crash report

 - OS: BigSur
 - 11.5.2
 - Laptop Model: t450 i5 5300U hd5500
 - WiFi-Bt: Intel 

The only edit is for the intel BT, i've alredy tryed to get a fresh install of mac os but after 1/2 days this append again!

Sorry for my bad english

![Schermata 2021-09-13 alle 00 38 19](https://user-images.githubusercontent.com/75070444/133736094-36344bec-70a9-466a-8cce-52e364903f59.png)
![Schermata 2021-09-13 alle 00 38 39](https://user-images.githubusercontent.com/75070444/133736103-05849325-1568-4f39-976b-296b0fd21832.png)

**Comment by racka98** [comment]
This is a macOS specific issue and probably not caused by this EFI. The crash happens on real macs too.
