### ISSUE TITLE
Dual Batteries not working

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#62]
**Describe the bug**
Dual batteries are not working, and I don't get the expected battery life. On Linux I get around 4-5 hours from my batteries. But on MacOS I only get 1 hour under light usage.

**Screenshots**
![image](https://user-images.githubusercontent.com/33642056/133931236-63f335cd-c718-4109-94ac-20ecc1ab8e79.png)
In MacOS running `neofetch` only shows one battery

On Linux running it shows both batteries
![image](https://user-images.githubusercontent.com/33642056/133931252-81fd9caa-71c0-4326-a8e9-01122fec245a.png)

**macOS Info:**
 - OS: Big Sur
 - Version 11.5.1
 - Laptop Model: x250

**Comment by racka98** [comment]
macOS will never show 2 batteries because it has never been directly supported by the OS (no MacBook has dual batteries). It will always show 1 battery even if both are detected.

The only way to know if both batteries are being detected or not is to use IORegistryExplorer. Get it from here: https://github.com/utopia-team/IORegistryExplorer/releases

On the search bar type "BAT" and send the screenshot.

Also, note that the second battery may not be working because this EFI is for T450 while you have an X250. They may be similar on most things but they are not identical, so SSDT patches made for battery on T450 may not work on X250

**Comment by nerdthatnoonelikes** [comment]
![image](https://user-images.githubusercontent.com/33642056/133931803-7031a84d-ec24-4722-935d-3b616ef4cd7e.png)
Both batteries are showing up. I will try a different EFI and see if that works. Thank you :)

**Comment by racka98** [comment]
What's the battery capacity being reported by System Information under Hardware > Power ?

If it doesn't show the full capacity of both batteries then it's probably not working correctly

**Comment by fearlipe** [comment]
Well, i have the t450 and on System Information under Hardware > Power it shows only one time, not for "two" batteries. 
![Screen Shot 2021-09-19 at 11 53 51](https://user-images.githubusercontent.com/21061728/133932076-9119772c-cd0e-41bd-8fa4-e23003c0aec1.png)

**Comment by racka98** [comment]
> Well, i have the t450 and on System Information under Hardware > Power it shows only one time, not for "two" batteries. 
> ![Screen Shot 2021-09-19 at 11 53 51](https://user-images.githubusercontent.com/21061728/133932076-9119772c-cd0e-41bd-8fa4-e23003c0aec1.png)
> 

It will show 1 battery (even name for 1 battery) but the reported capacity is for two batteries. If you don't believe that then take out 1 battery, reboot your laptop and watch how the capacity becomes less than that (which will be the capacity of the single battery)

**Comment by fearlipe** [comment]
Oh i see, good!

**Comment by nerdthatnoonelikes** [comment]
> What's the battery capacity being reported by System Information under Hardware > Power ?
> 
> If it doesn't show the full capacity of both batteries then it's probably not working correctly

![image](https://user-images.githubusercontent.com/33642056/133932697-b7d0f108-42df-4b8c-a4c8-3a2c2ded310a.png)
This is what I see in system information

**Comment by fearlipe** [comment]
yes, second battery not working... "state of charge 62%" and "not charging".

**Comment by racka98** [comment]
Looks like both batteries are being reported. My batteries have more than 400 charge cycles but they still last for 3 hours and a half with light usage and 2 hrs with medum to heavy usage. Maybe the other battery is getting disconnected sometimes

**Comment by racka98** [comment]
> > What's the battery capacity being reported by System Information under Hardware > Power ?
> > 
> > If it doesn't show the full capacity of both batteries then it's probably not working correctly
> 
> ![image](https://user-images.githubusercontent.com/33642056/133932697-b7d0f108-42df-4b8c-a4c8-3a2c2ded310a.png)
> This is what I see in system information

Possibilities are either faulty battery or you have some kind of charge restrictions (the charging threshold feature) set om Linux/Windows that's possibly interfering with macOS battery management. As that feature usually gets applied at BIOS level

**Comment by nerdthatnoonelikes** [comment]
I haven't changed any battery settings on my Linux install as far as I know, and I have all the same BIOS settings as in the README.

**Comment by racka98** [comment]
Probably the just the T450 SSDT os not compatible with X250. Try other EFIs

**Comment by nerdthatnoonelikes** [comment]
Will do, Thanks for the help.
