### ISSUE TITLE
Headphones Issue

### ISSUE THREAD

**Issue by deurbroucq** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#64]
I cannot get headphones to work. Output and input with built-in speakers and mic work just fine. I am using release 0.7.0 with Big Sur 11.6.

ThinkPad T450s, i5-5300U, Realtek ALC292.

Any help would be appreciated. Thank you!

**Comment by fearlipe** [comment]
Sorry to hear that.

I do have a t450 working the headphone jack, but I don't remember what I've done for it to work... if you want I can provide my zipped EFI for you, but I'm not sure if it will work with the t450s.

**Comment by fearlipe** [comment]
Here it is: https://app.box.com/s/6xruq7h49th3x0sifzqpccmzrnidjkkf

**Comment by fearlipe** [comment]
Here you go:

Github: https://github.com/fearlipe/lenovo-T450-OPENCORE-EFI

Box: https://app.box.com/s/6xruq7h49th3x0sifzqpccmzrnidjkkf

**Comment by fearlipe** [comment]
Please, remember to boot using a EFI drive (Just like when you installed the Mac Os), to avoid having issues if it doesn't work.

**Comment by deurbroucq** [comment]
Thank you for the lightning-quick response. I am booting with an EFI drive. The new set of EFI files made the headphone mic work, but I am still not getting any sound, even with alc_fix_new. Both mic and sound are working in Windows. I will keep trying, and I will update this thread if I discover anything new. Thank you again!

**Comment by luanmateuz** [comment]
> > @fearlipe your EFI folder work in my Thinkpad T450, but, when i remove headphone and reconnect again, they not work.
> 
> Sad to hear that. Also sad that I don't have that laptop anymore, so I can't help you any further... I don't recall having that issue with my install, so maybe you got that issue related to the sleep/wake headphone glitch. I recommend you to reinstall from the scratch using my efi.

Probably I'll do this when I have time. I'm sad knowing you no have this laptop anymore, lol. 

Thank you for your support!

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
