### ISSUE TITLE
Stall on Booting Installer (progress bar)

### ISSUE THREAD

**Issue by step21** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#68]
**Describe the bug**
After booting from USB, the system at first starts fine, but then when the progress bar for starting the actual installer is shown it stalled. I now disabled watch dog though hopefully next time logs will be written to disk, but any info would be appreciated.

**To Reproduce**
Boot from USB, start "Install Monterey".

**Expected behavior**
For the installer to start correctly.

**Screenshots**

**macOS Info:**
 - OS: Monterey
 - Version 12.0.1
 - Laptop Model: T450s

**Additional context**
12 GB Ram, i7-5600u

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
