### ISSUE TITLE
Bluetooth does not show any devices that I can connect to.

### ISSUE THREAD

**Issue by NetMan134** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#69]
## Describe the bug
When I go to my Bluetooth Settings on macOS and want to connect to my Bluetooth Headphones, I cannot do that, because they don't show up. But on my phone they do.
Not even one device shows up, but there should be at least 3.
The laptop shows on my phone's Bluetooth page, and I can connect to it with my phone and it shows up.
But the problem is I can't connect to any device from the macOS.

## Expected behavior
New Bluetooth devices show up in macOS Settings.

## Screenshots
![image](https://user-images.githubusercontent.com/46296255/140622231-671ab09c-738f-405f-b688-202164c8c61b.png)
![image](https://user-images.githubusercontent.com/46296255/140622254-2f51bb37-eff1-4156-a91c-9725644c7836.png)

## macOS Info:
 - OS: Big Sur
 - Version 11.5.2
 - Laptop Model: T450
![image](https://user-images.githubusercontent.com/46296255/140622279-13d7be6d-9d39-43a6-b7c2-7ba3832ed6db.png)

# Thanks for advice!

**Comment by lukasdk6** [comment]
Hello, 

I'm running with the same "problem" using the Big Sur. 

if you try to disable the wifi, you will be able to find bluetooth devices. 

I'm using the "Magic Keyboard" right now, using the T450 like a Mac mini. 

But, only works with the wifi turned off. 

Regards,

**Comment by NetMan134** [comment]
Thanks for your response, it works!
I consider this issue as closed.

sob., 6 lis 2021, 21:46 użytkownik Lucas Oliveira ***@***.***>
napisał:
