### ISSUE TITLE
unable to use wifi and no sound for earphone

### ISSUE THREAD

**Issue by jasonchanlol** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#7]
I'm using a ax200 and it seems not working. And also there is no sound when I plug in my earphone. I'm a newbie for opencore, I've been checking these issues online for few days, and none of the methods work.I'll so grateful if anybody can help to solve it.

**Comment by racka98** [comment]
> I'm using a ax200 and it seems not working. And also there is no sound when I plug in my earphone. I'm a newbie for opencore, I've been checking these issues online for few days, and none of the methods work.I'll so grateful if anybody can help to solve it. 

There is a known issue with the jack. It only works when you put the laptop to sleep and wake it up after every first boot. Try installing the alc_fix in Utilities folder to fix this issue. Although alc_fix seems to be spotty on Big Sur.

For that wifi card i think driver support by itlwm is not very good. It seems to be a proprietary card for oems with proprietary drivers. People have had success with it but most have reported it not working. I suggest you use the stock wifi card or buy a macOS compatible card

**Comment by jasonchanlol** [comment]
thank you for replying me. I used the configurator to force io8blablabla.Kext running and the WiFi seems working pretty well with the airportltlwm, while I still don’t know fix the earphone issue

**Comment by jasonchanlol** [comment]
> > I'm using a ax200 and it seems not working. And also there is no sound when I plug in my earphone. I'm a newbie for opencore, I've been checking these issues online for few days, and none of the methods work.I'll so grateful if anybody can help to solve it.
> 
> There is a known issue with the jack. It only works when you put the laptop to sleep and wake it up after every first boot. Try installing the alc_fix in Utilities folder to fix this issue. Although alc_fix seems to be spotty on Big Sur.
> 
> For that wifi card i think driver support by itlwm is not very good. It seems to be a proprietary card for oems with proprietary drivers. People have had success with it but most have reported it not working. I suggest you use the stock wifi card or buy a macOS compatible card

don‘t know if I am using alc_fix correctly, the earphone only works for the first plug in after reboot, if I remove it and replug it doesn’t work again.

**Comment by racka98** [comment]
> > > I'm using a ax200 and it seems not working. And also there is no sound when I plug in my earphone. I'm a newbie for opencore, I've been checking these issues online for few days, and none of the methods work.I'll so grateful if anybody can help to solve it.
> > 
> > There is a known issue with the jack. It only works when you put the laptop to sleep and wake it up after every first boot. Try installing the alc_fix in Utilities folder to fix this issue. Although alc_fix seems to be spotty on Big Sur.
> > 
> > For that wifi card i think driver support by itlwm is not very good. It seems to be a proprietary card for oems with proprietary drivers. People have had success with it but most have reported it not working. I suggest you use the stock wifi card or buy a macOS compatible card
> 
> don‘t know if I am using alc_fix correctly, the earphone only works for the first plug in after reboot, if I remove it and replug it doesn’t work again.

Uninstall the previous one using ```
sh uninstall.sh
```

Then install this [one](https://www.github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/Utilities%2Falc_fix_swift) as per instructions i attached in the README.md kf Utilities folder

See if this fixes your issues, it's a new improved one

**Comment by jasonchanlol** [comment]
> > > > I'm using a ax200 and it seems not working. And also there is no sound when I plug in my earphone. I'm a newbie for opencore, I've been checking these issues online for few days, and none of the methods work.I'll so grateful if anybody can help to solve it.
> > > 
> > > 
> > > There is a known issue with the jack. It only works when you put the laptop to sleep and wake it up after every first boot. Try installing the alc_fix in Utilities folder to fix this issue. Although alc_fix seems to be spotty on Big Sur.
> > > For that wifi card i think driver support by itlwm is not very good. It seems to be a proprietary card for oems with proprietary drivers. People have had success with it but most have reported it not working. I suggest you use the stock wifi card or buy a macOS compatible card
> > 
> > 
> > don‘t know if I am using alc_fix correctly, the earphone only works for the first plug in after reboot, if I remove it and replug it doesn’t work again.
> 
> Uninstall the previous one using
> 
> ```
> sh uninstall.sh
> ```
> 
> Then install this [one](https://www.github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/Utilities%2Falc_fix_swift) as per instructions i attached in the README.md of Utilities folder
> 
> See if this fixes your issues, it's a new improved one

thanks a lot for the helps. May I ask one more question ?the hidpi thing seems making no change on sharpness,unlike those picture online showing much difference,the only change I could found is that my monitor becomes retina monitor in the setting, is it normal ？

**Comment by racka98** [comment]
Is your monitor high dpi? It's supposed to be a 1440p and a ove monitor to see an increase in sharpness. Or if it's 1080p it should have a DPI of at least 300
