### ISSUE TITLE
I want to back to windows

### ISSUE THREAD

**Issue by lamrigel** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#71]
Guys i want get back to windows i copied windows install files but when i try to boot it's wont boot  any help

**Comment by V3ntus** [comment]
Elaborate "copied install files"?
You need to do a full wipe since Windows is not compatible with any of the Mac file system. Then install Windows

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
