### ISSUE TITLE
Works beautifully apart from the audio

### ISSUE THREAD

**Issue by crazD802** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#8]
Hi,

When I initially installed via USB I had audio - both speaker and mic.

Now, when booting up from the SSD, I have no audio, none at all. No devices are listed in audio preferences

**macOS Info:**
 - OS: [Big Sur]
 - Version [11.1]
 - Laptop Model: T450s

This is my third Hackintosh and first laptop, and easily the easiest of all 3. This is the only problem I've had. Thanks a million!!!

**Comment by racka98** [comment]
> Hi,
> 
> When I initially installed via USB I had audio - both speaker and mic.
> 
> Now, when booting up from the SSD, I have no audio, none at all. No devices are listed in audio preferences
> 
> **macOS Info:**
>  - OS: [Big Sur]
>  - Version [11.1]
>  - Laptop Model: T450s
> 
> This is my third Hackintosh and first laptop, and easily the easiest of all 3. This is the only problem I've had. Thanks a million!!!

That's odd. Have you tried clearing NVRAM? Clear it and see if solves the problem. You clear NVRAM from the boot selector

**Comment by crazD802** [comment]
Hi Thanks for getting back to me. This is even stranger. I was trying to narrow it down and get some more info, and in doing so restarted a few times, each time the start-up tone played. Then the last time it got stuck in a loop of playing the start-up tone so I had to hold the power button to reboot properly. On rebooting this time the audio is now fine. Has that boot loop and me powering off with the button cleared the NVRAM???

Thanks again!

**Comment by racka98** [comment]
> Hi Thanks for getting back to me. This is even stranger. I was trying to narrow it down and get some more info, and in doing so restarted a few times, each time the start-up tone played. Then the last time it got stuck in a loop of playing the start-up tone so I had to hold the power button to reboot properly. On rebooting this time the audio is now fine. Has that boot loop and me powering off with the button cleared the NVRAM???
> 
> Thanks again!

The startput tone may be causing problems. Disable boot chime in config.plist

**Comment by crazD802** [comment]
I've done that, no audio again. Reset NVRAM still no audio.

Is this screenshot correct? I'm new to opencore. in clover I'm thinking that's wrong...

<img width="608" alt="Screenshot 2021-01-08 at 17 25 46" src="https://user-images.githubusercontent.com/77158837/104045608-b9faba80-51d6-11eb-9b92-9eed2b39d114.png">

**Comment by crazD802** [comment]
Hmmm. 2 successful restarts with audio after, on the 3rd attempt no audio again.

**Comment by crazD802** [comment]
A few more restarts and a "cut the power" and still no audio.

**Comment by crazD802** [comment]
Reset NVRAM. Still not working. This seems to follow no pattern....

This maybe something, the "play sound on startup" checkbox in Sound Preferences seems to change. I had turned it off, now its back on. Ill turn it off and see what that does.

**Comment by crazD802** [comment]
That doesn't make a difference.

**Comment by racka98** [comment]
1. Delete AudioDxe.efi in Config.plist under NVRAM/Drivers and in OC/Driver folder
![Screenshot 2021-01-08 at 20 54 37](https://user-images.githubusercontent.com/41214249/104048247-f7ba0c00-51f3-11eb-9250-fb1e6d560e41.png)

2. Delete the value in SystemAudioVolume as shown in the screenshot
![Screenshot 2021-01-08 at 20 54 48](https://user-images.githubusercontent.com/41214249/104048349-22a46000-51f4-11eb-81b1-a48d6a7e64af.png)

3. Change all values under UEFI/Audio to match the screenshot below
![Screenshot 2021-01-08 at 21 01 16](https://user-images.githubusercontent.com/41214249/104048620-98a8c700-51f4-11eb-8cf3-d4616631fe35.png)

4. Lastly delete the Audio folder under OC/Resources

That's how you disable bootchime.

After disabling these, clear NVRAM in boot menu then reboot the computer again and see if that fixes it

**Comment by crazD802** [comment]
Hey! Audio now works. I'll do a few restarts...

Thanks for your help, I'll let you know what happens...

**Comment by crazD802** [comment]
Nope. It's still seemingly random. Sometimes audio works, other times it doesn't. Sometimes resetting the NVRAM works sometimes it doesn't.

**Comment by racka98** [comment]
> Nope. It's still seemingly random. Sometimes audio works, other times it doesn't. Sometimes resetting the NVRAM works sometimes it doesn't.

Ok i think there's am inconsistent initialization of AppleALC.

Can you please run this in terminal:
```
kextstat | grep -E "AppleHDA|AppleALC|Lilu
```

And send the output. Run this when audio doesn't work

**Comment by crazD802** [comment]
Aha, out of curiosity I ran that when audio did work, this is when it didn't, its different:

<img width="1152" alt="Screenshot 2021-01-08 at 19 16 53" src="https://user-images.githubusercontent.com/77158837/104055193-3e086e80-51e6-11eb-8214-7ce8559a110f.png">

**Comment by crazD802** [comment]
This is when audio works, but I guess you will know this already...

<img width="1148" alt="Screenshot 2021-01-08 at 19 22 48" src="https://user-images.githubusercontent.com/77158837/104055651-0948e700-51e7-11eb-9230-e06dec90e896.png">

**Comment by crazD802** [comment]
This is in Hackintool when it works, when there is no audio the entire panel is empty. The last value is Max Kernel 15, FWIW...

<img width="644" alt="Screenshot 2021-01-08 at 19 26 18" src="https://user-images.githubusercontent.com/77158837/104055863-647ad980-51e7-11eb-99d1-122c9cf00b3c.png">

**Comment by racka98** [comment]
> This is when audio works, but I guess you will know this already...
> 
> <img width="1148" alt="Screenshot 2021-01-08 at 19 22 48" src="https://user-images.githubusercontent.com/77158837/104055651-0948e700-51e7-11eb-9230-e06dec90e896.png">
> 

Aha, AppleHDA is not being initialized on boot. Inside config.plist in boot-args enter alcdelay=1000 (make sure their a space between this arg and the keepsysm=1 arg

**Comment by crazD802** [comment]
Yes! after I reset the NVRAM its survived 10 reboots and worked every time. Thanks so much, that's amazing!

**Comment by racka98** [comment]
> Yes! after I reset the NVRAM its survived 10 reboots and worked every time. Thanks so much, that's amazing!

No problem

**Comment by cchyswy** [comment]
Hello, my 450S is now waking up after sleep. There is no sound in the video, so I just need to restart it. Is this related to ALC Fix



> This is in Hackintool when it works, when there is no audio the entire panel is empty. The last value is Max Kernel 15, FWIW...
> 
> <img alt="Screenshot 2021-01-08 at 19 26 18" width="644" src="https://user-images.githubusercontent.com/77158837/104055863-647ad980-51e7-11eb-99d1-122c9cf00b3c.png">


My sound card is also displayed in Hackintool, which already has alcdelay=1000 in the config!

**Comment by racka98** [comment]
> Hello, my 450S is now waking up after sleep. There is no sound in the video, so I just need to restart it. Is this related to ALC Fix
> 
> 
> 
> > This is in Hackintool when it works, when there is no audio the entire panel is empty. The last value is Max Kernel 15, FWIW...
> > 
> > <img alt="Screenshot 2021-01-08 at 19 26 18" width="644" src="https://user-images.githubusercontent.com/77158837/104055863-647ad980-51e7-11eb-99d1-122c9cf00b3c.png">
> 
> 
> My sound card is also displayed in Hackintool, which already has alcdelay=1000 in the config!
> 

Do you have codeccommander kext enabled??

**Comment by cchyswy** [comment]
Yes. Codecommander has been loaded, do I need to stop this and replace it with another alc_fix?

**Comment by racka98** [comment]
> Yes. Codecommander has been loaded, do I need to stop this and replace it with another alc_fix?

Codeccommander should be left enabled. Maybe you have too many instances of alc_fix. How many did you install?

**Comment by cchyswy** [comment]
I seem to have installed alc_fix several times. Now I switch to alc_fix_swift and disable Codeccommander. The problem still seems to be the same. When I switch to alc_fix_swift, I uninstall.sh first and then install it. I haven’t reset NVRAM yet. I will reset NVRAM later. Test to see if the problem can be solved.

**Comment by racka98** [comment]
> I seem to have installed alc_fix several times. Now I switch to alc_fix_swift and disable Codeccommander. The problem still seems to be the same. When I switch to alc_fix_swift, I uninstall.sh first and then install it. I haven’t reset NVRAM yet. I will reset NVRAM later. Test to see if the problem can be solved.

Don't turn off codeccommander

**Comment by cchyswy** [comment]
This folder contains instructions to install the new swift version of alc_fix which doesn't rely on hda-verb, alc-verb or CodecCommander kext. The installation process is in the folder.

Don't turn off codeccommander？？Isn't codeccommander okay with alx_fix_swift? There is a new problem now. The earphones are all noisy. I haven't tested the audio problem after sleep.

The current configuration is as follows: Load codeccommander, use alc_fix_swift this repair script

<img width="582" alt="屏幕快照 2021-03-29 14 27 48" src="https://user-images.githubusercontent.com/56290776/112796283-575de000-909c-11eb-9e8f-0968164264de.png">
<img width="582" alt="屏幕快照 2021-03-29 14 31 59" src="https://user-images.githubusercontent.com/56290776/112796311-60e74800-909c-11eb-9975-70a79f5492b0.png">

**Comment by racka98** [comment]
> @racka98 I'm having the same issue on my T450 with Mojave. Works perfect, but as soon as I wake-from-sleep, no sound
> 

Is codeccommander turned on?

**Comment by shtefanilie** [comment]
> Is codeccommander turned on?
![Screenshot 2021-05-01 at 20 07 05](https://user-images.githubusercontent.com/44569938/116792516-0422e700-aab9-11eb-8c1e-27af67954228.png)
YYeep.

**Comment by racka98** [comment]
> > Is codeccommander turned on?
> 
> ![Screenshot 2021-05-01 at 20 07 05](https://user-images.githubusercontent.com/44569938/116792516-0422e700-aab9-11eb-8c1e-27af67954228.png)
> YYeep.
> 
> Edit: When I plug in my headphones via the jack, it get only static.

The static noise i a known that has no fix currently.

Try using the new OC 0.6.8 i just published to see if you still get the volume loss issue

**Comment by shtefanilie** [comment]
Updated to `0.6.8`, but still missing sound after wake. And also, static noise.

**Comment by racka98** [comment]
> Updated to `0.6.8`, but still missing sound after wake. And also, static noise.

Static has no fix currently. Temporary fix is to put the laptop to sleep then wake. Headphones should not have any static.
(I'm planning on fixing this).

For the loss of sound can you try running a fresh copy of the entire EFI from this repo without modifying anything to see if still has that problem.

**Comment by racka98** [comment]
> This folder contains instructions to install the new swift version of alc_fix which doesn't rely on hda-verb, alc-verb or CodecCommander kext. The installation process is in the folder.
> 
> Don't turn off codeccommander？？Isn't codeccommander okay with alx_fix_swift? There is a new problem now. The earphones are all noisy. I haven't tested the audio problem after sleep.
> 
> The current configuration is as follows: Load codeccommander, use alc_fix_swift this repair script
> 
> <img width="582" alt="屏幕快照 2021-03-29 14 27 48" src="https://user-images.githubusercontent.com/56290776/112796283-575de000-909c-11eb-9e8f-0968164264de.png">
> <img width="582" alt="屏幕快照 2021-03-29 14 31 59" src="https://user-images.githubusercontent.com/56290776/112796311-60e74800-909c-11eb-9975-70a79f5492b0.png">
> 
> 

Alc_swift doesn't seem to work. You should probably remove it. Only codeccommander works. I'll check other alc IDs to see they solve the issue
